name: gemini
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:
  google_generative_ai:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner:
  riverpod_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
